-- HOR DEFINES --

-- MEDAL DEFINES --
NDefines.NMilitary.COST_INCREASE_PER_ACTIVE_MEDAL = 0 -- USED TO BE 0.25

-- CONSUMER GOOD DEFINES --
NDefines.NProduction.MINIMUM_NUMBER_OF_FACTORIES_TAKEN_BY_CONSUMER_GOODS_VALUE = 0
NDefines.NProduction.MINIMUM_NUMBER_OF_FACTORIES_TAKEN_BY_CONSUMER_GOODS_PERCENT = 0

-- MAX BUILDING LEVELS DEFINES
NDefines.NBuildings.MAX_BUILDING_LEVELS = 50 -- USED TO BE 15

-- HIGHER CHANCE TO GET A HIT TO DAMAGE ON FORTS (OUT OF 100) DEFINES
NDefines.NMilitary.LAND_COMBAT_FORT_DAMAGE_CHANCE = 10 -- USED TO BE 5

-- RESOURCE LACK PENALTY ON PRODUCTION LINE DEFINES -- 
NDefines.NProduction.PRODUCTION_RESOURCE_LACK_PENALTY = -0.005 -- USED TO BE -0.05

-- CHEAPER GENERAL RECRUITING DEFINES --
NDefines.NPolitics.ARMY_LEADER_MAX_COST = 25.0 -- USED TO BE 80.0

-- BETTER PRESET COLORS DEFINES --
NDefines.NGraphics.COMMANDGROUP_PRESET_COLORS_HSV = {
		00.0/360.0, 0.95, 0.86,
		39.0/360.0, 0.95, 0.86,
		55.0/360.0, 0.95, 0.86,
		80.0/360.0, 0.95, 0.86,
		117.0/360.0, 0.95, 0.80,
		177.0/360.0, 0.95, 0.86,
		201.0/360.0, 0.95, 0.80,
		279.0/360.0, 0.95, 0.92,
		318.0/360.0, 0.95, 0.86,
		00.0/360.0, 0.00, 0.86
	}

-- GERMAN REWORK TECH DEFINES --
NDefines.ACCLIMATIZATION_IN_COMBAT_SPEED_FACTOR = 0.25
NDefines.ACCLIMATIZATION_SPEED_GAIN = 0.1
NDefines.ACCLIMATIZATION_LOSS_SPEED_FACTOR = 1.0
NDefines.NGraphics.WEATHER_DISTANCE_CUTOFF = 1200
NDefines.NGraphics.WEATHER_ZOOM_IN_CUTOFF = 1
NDefines.NGraphics.WEATHER_PLAYBACK_RATE = 0.25
NDefines.NGraphics.WEATHER_PLAYBACK_RATE_CUTOFF = 400
NDefines.NGraphics.WEATHER_PLAYBACK_RATE_LENGTH = 200

-- LINEAR XP GAIN DEFINES --
NDefines.NMilitary.UNIT_LEADER_USE_NONLINEAR_XP_GAIN = false

-- BETTER TANK DEFINES --
NDefines.NMilitary.ARMOR_VS_AVERAGE = 0.25 -- USED TO BE 0.4
NDefines.NMilitary.PEN_VS_AVERAGE = 0.3  -- USED TO BE 0.4

-- BETTER MECHANICS: STRATEGIC VIEW DEFINES --
-- NDefines_Graphics.NMapMode.MAP_MODE_MANPOWER_RANGE_COLOR_FROM = { 0.75, 0.75, 0.75, 1.0 }
-- NDefines_Graphics.NMapMode.MAP_MODE_MANPOWER_RANGE_COLOR_TO = { 0.0, 1.0, 0.0, 1.0 }

-- NDefines_Graphics.NMapMode.MAP_MODE_INFRA_RANGE_COLOR_FROM = { 0.75, 0.75, 0.75, 1.0 }
-- NDefines_Graphics.NMapMode.MAP_MODE_INFRA_RANGE_COLOR_TO = { 0.0, 1.0, 0.0, 1.0 }

----------------------------

NDefines_Graphics.NMapIcons.STRATEGIC_AIR_PRIORITY_AIR_MISSION = 290

NDefines_Graphics.NGraphics.VICTORY_POINT_MAP_ICON_TEXT_CUTOFF = {300, 500, 1500}

--NDefines_Graphics.NGraphics.MAP_ICONS_GROUP_MAX_SIZE = 0
NDefines_Graphics.NGraphics.MAP_ICONS_GROUP_CAM_DISTANCE = 100				--group moving and still units
NDefines_Graphics.NGraphics.MAP_ICONS_STATE_GROUP_CAM_DISTANCE = 450 ---1325.0		--group into states
NDefines_Graphics.NGraphics.MAP_ICONS_STRATEGIC_GROUP_CAM_DISTANCE = 700 ---1400		--group units into air regions
NDefines_Graphics.NGraphics.MAP_ICONS_STRATEGIC_AREA_HUGE = 220					--size limit for air region grouping
NDefines_Graphics.NGraphics.MAP_ICONS_STATE_HUGE = 100							--size limit for state grouping
NDefines_Graphics.NGraphics.MAPICON_GROUP_STRATEGIC_SIZE = 1000
NDefines_Graphics.NGraphics.MAP_ICONS_GROUP_SPLIT_SELECTED_LIMIT = 10
NDefines_Graphics.NGraphics.MAP_ICONS_COARSE_COUNTRY_GROUPING_DISTANCE = 125 --90 --200
NDefines_Graphics.NGraphics.MAP_ICONS_COARSE_COUNTRY_GROUPING_DISTANCE_STRATEGIC = 350

NDefines_Graphics.NGraphics.COMMANDGROUP_PRESET_COLORS_HSV = {
	0.0/360.0, 1.0, 0.75,	--red
	10.0/360.0, 1.0, 0.75,	--orange
	60.0/360.0, 1.0, 0.75,	--yellow
	120.0/360.0, 0.85, 0.75,	--green
	155.0/360.0, 1.0, 0.75,	--greenish
	180.0/360.0, 1.0, 0.75,	--turq
	220.0/360.0, 1.0, 0.75,	--blue
	260.0/360.0, 1.0, 0.85,	--dark purple
	330.0/360.0, 0, 0.75		--white
}

NDefines_Graphics.NGraphics.CAMERA_ZOOM_SPEED_DISTANCE_MULT = 20

--NDefines_Graphics.NGraphics.AIRBASE_ICON_DISTANCE_CUTOFF = 900
--NDefines_Graphics.NGraphics.NAVALBASE_ICON_DISTANCE_CUTOFF = 900

--NDefines_Graphics.NGraphics.UNIT_ARROW_DISTANCE_CUTOFF = 1000
--NDefines_Graphics.NGraphics.UNITS_ICONS_DISTANCE_CUTOFF = 900
--NDefines_Graphics.NGraphics.NAVAL_COMBAT_DISTANCE_CUTOFF = 1500
--NDefines_Graphics.NGraphics.ADJACENCY_RULE_DISTANCE_CUTOFF = 1700
--NDefines_Graphics.NGraphics.LAND_COMBAT_DISTANCE_CUTOFF = 1500
--NDefines_Graphics.NGraphics.SUPPLY_ICON_DISTANCE_CUTOFF = 2500
--NDefines_Graphics.NGraphics.PROV_CONSTRUCTION_ICON_DISTANCE_CUTOFF = 400
--NDefines_Graphics.NGraphics.STATE_CONSTRUCTION_ICON_DISTANCE_CUTOFF = 800

NDefines_Graphics.NGraphics.STRATEGIC_AIR_COLOR_BAD = {0.65, 0, 0, 1}
NDefines_Graphics.NGraphics.STRATEGIC_AIR_COLOR_GOOD = {0, 0.65, 0, 1}
NDefines_Graphics.NGraphics.STRATEGIC_AIR_COLOR_AVERAGE = {0.65, 0.65, 0, 1}
NDefines_Graphics.NGraphics.STRATEGIC_AIR_COLOR_NEUTRAL = {130.0/255, 130.0/255, 130.0/255, 1}

NDefines_Graphics.NGraphics.GRADIENT_BORDERS_THICKNESS_STRATEGIC_REGIONS = 250.0
NDefines_Graphics.NGraphics.GRADIENT_BORDERS_THICKNESS_SUPPLY_AREA_A = 250 --250.0
NDefines_Graphics.NGraphics.GRADIENT_BORDERS_THICKNESS_SUPPLY_AREA_B = 250 --250.0
	
NDefines_Graphics.NGraphics.RESISTANCE_COLOR_GOOD = {0.0, 0.65, 0, 1}
NDefines_Graphics.NGraphics.RESISTANCE_COLOR_AVERAGE = {0.65, 0.65, 0, 1}
NDefines_Graphics.NGraphics.RESISTANCE_COLOR_BAD = {0.65, 0, 0, 1}
	
NDefines_Graphics.NGraphics.STRATEGIC_NAVY_COLOR_MISSION = {0.65, 0.65, 0.0, 1}
--NDefines_Graphics.NGraphics.STRATEGIC_NAVY_COLOR_NEUTRAL = {130.0/255, 130.0/255, 130.0/255, 1}

NDefines_Graphics.NGraphics.ROOT_FRONT_OFFSET = 2

--NDefines_Graphics.NGraphics.VIRTUAL_BATTLEPLANS_COLOR = { 1.0, 0.0, 0.0, 1 }

--NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_STATE_R = 0.5	--state connected to province
--NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_STATE_G = 0.5
--NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_STATE_B = 0.5
--NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_STATE_A = 1.0
--NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_SUPPLY_AREA_R = 0.6
--NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_SUPPLY_AREA_G = 0.2
--NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_SUPPLY_AREA_B = 0.6
--NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_SUPPLY_AREA_A = 1.0
--NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_ADJACENCY_RULE_AREA_R = 0.0
--NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_ADJACENCY_RULE_AREA_G = 1.0
--NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_ADJACENCY_RULE_AREA_B = 1.0
--NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_ADJACENCY_RULE_AREA_A = 1.0
--NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_BUILDING_AREA_R = 1.0
--NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_BUILDING_AREA_G = 1.0
--NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_BUILDING_AREA_B = 1.0
--NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_BUILDING_AREA_A = 1.0
--NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_PROVINCE_R = 1.0 --selected province or region
--NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_PROVINCE_G = 1.0
--NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_PROVINCE_B = 0.0
--NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_PROVINCE_A = 1.0
--NDefines_Graphics.NGraphics.BORDER_COLOR_CUSTOM_HIGHLIGHT_R = 0.0
--NDefines_Graphics.NGraphics.BORDER_COLOR_CUSTOM_HIGHLIGHT_G = 0.61
--NDefines_Graphics.NGraphics.BORDER_COLOR_CUSTOM_HIGHLIGHT_B = 0.75
--NDefines_Graphics.NGraphics.BORDER_COLOR_CUSTOM_HIGHLIGHT_A = 1.0
--NDefines_Graphics.NGraphics.WATER_MAP_MODE_COLOR_R = 1.0
--NDefines_Graphics.NGraphics.WATER_MAP_MODE_COLOR_G = 0.0
--NDefines_Graphics.NGraphics.WATER_MAP_MODE_COLOR_B = 0.0

--NDefines_Graphics.NGraphics.BORDER_WIDTH = 2

-- AIRPORT, DOCKYARD & RADAR
NDefines_Graphics.NGraphics.AIRBASE_ICON_DISTANCE_CUTOFF = 500
NDefines_Graphics.NGraphics.NAVALBASE_ICON_DISTANCE_CUTOFF = 500
NDefines_Graphics.NGraphics.RADAR_ICON_DISTANCE_CUTOFF = 500

-- !MORE UNIT LEVELS - VANILLA RANGE DEFINES --
NDefines.NMilitary.TRAINING_MAX_LEVEL = 10
NDefines.NMilitary.DEPLOY_TRAINING_MAX_LEVEL = 5
NDefines.NMilitary.UNIT_EXP_LEVELS = {0.02,	0.04,	0.06,	0.08,	0.1,	0.14,	0.18,	0.22,	0.26,	0.3,	0.39,	0.48,	0.57,	0.66,	0.75,	0.78,	0.81,	0.84,	0.87,	0.9}		-- Experience needed to progress to the next level
NDefines.NMilitary.EXPERIENCE_COMBAT_FACTOR = 0.05
NDefines.NMilitary.ARMY_EXP_BASE_LEVEL = 5
-- NDefines.NAir.AIR_WING_XP_LEVELS = { 20, 40, 60, 80, 100, 140, 180, 220, 260, 300, 380, 460, 640, 620, 700, 740, 780, 820, 860, 900 }

-- VOLUNTEER DEFINES --
NDefines.NDiplomacy.VOLUNTEERS_RETURN_EQUIPMENT = 1.0 -- USED TO BE 0.95
NDefines.NDiplomacy.VOLUNTEERS_TRANSFER_SPEED = 3 -- USED TO BE 14
NDefines.NDiplomacy.VOLUNTEERS_DIVISIONS_REQUIRED = 0 -- USED TO BE 30

-- AIR DEFINES --
NDefines.NAir.AIR_WING_FLIGHT_SPEED_MULT = 0.2 -- USED TO BE 0.02
NDefines.NAir.AIR_DEPLOYMENT_DAYS = 0 -- USED TO BE 3

-- ARMY TRAINING DEFINES --
NDefines.NProduction.MIN_POSSIBLE_TRAINING_MANPOWER = 1000000000 -- USED TO BE 100000

-- GAME STABILITY DEFINES --
NDefines.NCountry.INTERPOLATED_FRONT_STEPS_SHORT = 1 -- USED TO BE 2 - PERFORMANCE OPTIMIZATION - THE AMOUNT OF STEPS FOR INTERPOLATED FRONTS. NON-AI COUNTRIES GOT FULL INTERPOLATED FRONTS, THE REST HAS OPTIMIZED VERSION OF IT.
NDefines.NGame.MESSAGE_TIMEOUT_DAYS = 14 -- USED TO BE 60 - LESS MESSAGES LYING AROUND AT THE TOP OF YOUR SCREEN
NDefines.NCountry.EVENT_PROCESS_OFFSET = 30 -- Performance enhancer. --TW/WTT
NDefines.NGame.HANDS_OFF_START_TAG = "CNT" -- USED TO BE "HAI"
NDefines.NGame.LAG_DAYS_FOR_LOWER_SPEED = 1000 -- USED TO BE 10
NDefines.NGame.LAG_DAYS_FOR_PAUSE = 1100 -- USED TO BE 25
NDefines.NGame.COMBAT_LOG_MAX_MONTHS = 14 -- CUTS DOWN ON SAVEFILE SIZE
NDefines_Graphics.NGraphics.MAPICON_GROUP_PASSES = 10 -- USED TO BE 20
NDefines.NGame.GAME_SPEED_SECONDS = { 3.0, 0.25, 0.18, 0.06, 0.0 } -- USED TO BE 2.0, 0.5, 0.2, 0.1, 0.0

-- FUEL DEFINES --
NDefines.NCountry.BASE_FUEL_GAIN_PER_OIL = 0.5 -- FROM 2 -> 0.5
NDefines.NCountry.BASE_FUEL_GAIN  = 1.0 -- FROM 2.0 -> 1.0
NDefines.NCountry.BASE_FUEL_CAPACITY = 100000 -- FROM 50000 -> 100000
NDefines.NMilitary.ARMY_COMBAT_FUEL_MULT = 2.0 -- FROM 1.0 -> 2.0
NDefines.NMilitary.ARMY_TRAINING_FUEL_MULT = 2.0 -- FROM 1.0 -> 2.0
NDefines.NMilitary.ARMY_MOVEMENT_FUEL_MULT = 2.0 -- FROM 1.0 -> 2.0
NDefines.NAI.MAX_FUEL_CONSUMPTION_RATIO_FOR_NAVY_TRAINING = 0.40 -- FROM 0.20 -> 0.40
NDefines.NAI.MAX_FUEL_CONSUMPTION_RATIO_FOR_AIR_TRAINING = 0.40 -- FROM 0.20 -> 0.40

-- CONVOY AND LEND LEASE DEFINES --
NDefines.NCountry.FUEL_LEASE_CONVOY_RATIO = 0.00005 -- USED TO BE 0.0005
NDefines.NCountry.SUPPLY_CONVOY_FACTOR = 0.025 -- USED TO BE 0.25

-- ATTACHE PP AND CP COST DEFINES --
NDefines.NDiplomacy.BASE_SEND_ATTACHE_COST = 50 -- USED TO BE 100
NDefines.NDiplomacy.BASE_SEND_ATTACHE_CP_COST = 25.0 -- USED TO BE 50

-- CIVS, MILS AND DOCS IC OUTPUT AND MAX MILS ON A LINE DEFINES --
NDefines.NProduction.BASE_FACTORY_SPEED = 2 -- USED TO BE 4
NDefines.NProduction.BASE_FACTORY_SPEED_MIL = 2 -- USED TO BE 3.5
NDefines.NProduction.BASE_FACTORY_SPEED_NAV = 1.5 -- USED TO BE 2.0
NDefines.NProduction.MAX_MIL_FACTORIES_PER_LINE = 200 -- USED TO BE 150
NDefines.NProduction.MAX_MIL_FACTORIES_VISIBLE_FOR_MIL_EQUIPMENT_LINE = 200 -- USED TO BE 15

-- XP, PP AND CP DEFINES --
NDefines.NCountry.POLITICAL_POWER_UPPER_CAP = 9999.9;
NDefines.NCountry.BASE_MAX_COMMAND_POWER = 999.9;
NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 999;
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 999;
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 999;

-- DIVISION DESIGNER DEFINES --
NDefines.NMilitary.MAX_DIVISION_SUPPORT_HEIGHT = 6 -- USED TO BE 5 

-- MAX 10 FACTORIES/DOCKYARDS FOR RAILWAY GUNS AND FLOATING HARBORS DEFINES --
NDefines.NProduction.FLOATING_HARBOR_MAX_NAV_FACTORIES_PER_LINE = 10
NDefines.NProduction.RAILWAY_GUN_MAX_MIL_FACTORIES_PER_LINE = 10;

-- 50 BUILDING SLOTS PER STATE DEFINES --
NDefines.NBuildings.MAX_SHARED_SLOTS = 50 -- USED TO BE 25

-- INCREASED GENERAL AND FIELD MARSHAL DIVISION AND ARMY LIMITS DEFINES --
NDefines.NMilitary.CORPS_COMMANDER_DIVISIONS_CAP = 40 -- USED TO BE 24
NDefines.NMilitary.CORPS_COMMANDER_ARMIES_CAP = -1				
NDefines.NMilitary.FIELD_MARSHAL_DIVISIONS_CAP = 40	-- USED TO BE 24
NDefines.NMilitary.FIELD_MARSHAL_ARMIES_CAP = 6 -- USED TO BE 5 

-- DIVISION EDITING, LAND, NAVAL AND AIR DESIGNER MODULES AND EQUIPMENT UPGRADES XP COSTS DEFINES --
NDefines.NMilitary.BASE_DIVISION_BRIGADE_GROUP_COST = 8 -- USED TO BE 20
NDefines.NMilitary.BASE_DIVISION_BRIGADE_CHANGE_COST = 2 -- USED TO BE 5
NDefines.NMilitary.BASE_DIVISION_SUPPORT_SLOT_COST = 4 -- USED TO BE 10
NDefines.NMilitary.LAND_EQUIPMENT_BASE_COST = 15 -- USED TO BE 10
NDefines.NMilitary.LAND_EQUIPMENT_RAMP_COST = 15 -- USED TO BE 5
NDefines.NMilitary.AIR_EQUIPMENT_BASE_COST = 35 -- USED TO BE 25
NDefines.NMilitary.AIR_EQUIPMENT_RAMP_COST = 10 -- USED TO BE 5
NDefines.NProduction.EQUIPMENT_MODULE_ADD_XP_COST = 1.0 -- USED TO BE 5.0
NDefines.NProduction.EQUIPMENT_MODULE_REPLACE_XP_COST = 2.0 -- USED TO BE 6.0
NDefines.NProduction.EQUIPMENT_MODULE_CONVERT_XP_COST = 1.0 -- USED TO BE 3.0

-- INCREASED SAVED DAYS ON RESEARCH AND BASE TECH COST DEFINES --
NDefines.NTechnology.BASE_RESEARCH_POINTS_SAVED = 75.0 -- USED TO BE 30.0
NDefines.NTechnology.BASE_TECH_COST = 100 -- USED TO BE 110

-- MAX FOCUS SAVED DAYS AMOUNT DEFINES --
NDefines.NFocus.MAX_SAVED_FOCUS_PROGRESS = 35 -- USED TO BE 10

-- AI ACCEPTING STUFF DEFINES --
NDefines.NDiplomacy.LICENSE_ACCEPTANCE_SAME_FACTION = 500 -- USED TO BE 20
NDefines.NDiplomacy.LICENSE_ACCEPTANCE_OPINION_FACTOR = 500 -- USED TO BE 0.4
NDefines.NAI.DIPLOMACY_ACCEPT_ATTACHE_BASE = 500
NDefines.NAI.DIPLOMACY_ACCEPT_VOLUNTEERS_BASE = 500
NDefines.NAI.DIPLOMACY_ACCEPT_ATTACHE_OPINION_TRASHHOLD = 0
NDefines.NAI.DIPLOMACY_ACCEPT_ATTACHE_OPINION_PENALTY = 0
NDefines.NAI.MINIMUM_CONVOY_TO_ASK_LEND_LEASE = 0
NDefines.NAI.GIVE_STATE_CONTROL_MIN_CONTROLLED = 0
NDefines.NAI.GIVE_STATE_CONTROL_MIN_CONTROL_DIFF = 0

--  LICENSING DEFINES --
NDefines.NProduction.LICENSE_IC_COST_YEAR_INCREASE = 0.25 -- USED TO BE 1
NDefines.NProduction.LICENSE_EQUIPMENT_BASE_SPEED = -0.20 -- USED TO BE -0.25 
NDefines.NProduction.LICENSE_EQUIPMENT_SPEED_NOT_FACTION = -0.20 -- USED TO BE -0.10
NDefines.NProduction.LICENSE_EQUIPMENT_TECH_SPEED_MAX_YEARS = 3 -- USED TO BE 4

-- NAVAL INVASION DEFINES --
NDefines.NNavy.NAVAL_INVASION_PREPARE_DAYS = 30 -- USED TO BE 60
NDefines.NNavy.NAVAL_INVASION_PLAN_CAP = 0 -- USED TO BE 1 
NDefines.NNavy.BASE_NAVAL_INVASION_DIVISION_CAP = 0 -- USED TO BE 4

-- FACTION DEFINES --
NDefines.NFactions.NFACTION_ASSIGN_SCIENTIST_COST = 0 -- USED TO BE 25
NDefines.NFactions.MAX_NUM_SHORT_TERM_GOALS = 3	-- USED TO BE 1 
NDefines.NFactions.MAX_NUM_MEDIUM_TERM_GOALS = 2 -- USED TO BE 1

-- DOCTRINE DEFINES --
NDefines.NDoctrines.DEFAULT_REWARD_MASTERY = 50.0 -- USED TO BE 100.0
NDefines.NDoctrines.BASE_MASTERY_GAIN_TARGET_MANPOWER = 1000000.0 -- USED TO BE 100000.0
NDefines.NDoctrines.MAX_MONTHLY_MASTERY_GAIN = 80.0 -- USED TO BE 40.0
NDefines.NDoctrines.MASTERY_BANK_MAX = 400.0 -- USED TO BE 200.0
NDefines.NDoctrines.MILITARY_ATTACHE_MASTERY_TRANSFER_FACTOR = 0.2 -- USED TO BE 0.1
NDefines.NDoctrines.TRAINING_MASTERY_GAIN_FACTOR = 0.2 -- USED TO BE 0.1
NDefines.NDoctrines.MASTERY_BANK_CONVERSION_RATE = 0.50 -- USED TO BE 0.25
NDefines.NDoctrines.NAVAL_MISSION_MASTERY_GAIN_FACTORS = {
		0.0, -- HOLD
		0.4, -- PATROL -- USED TO BE 0.2
		0.0, -- STRIKE FORCE
		0.4, -- CONVOY RAIDING -- USED TO BE 0.2
		0.4, -- CONVOY ESCORT -- USED TO BE 0.2
		0.4, -- MINES PLANTING -- USED TO BE 0.2
		0.4, -- MINES SWEEPING -- USED TO BE 0.2
		0.0, -- TRAIN # NOT USED - handled by TRAINING_MASTERY_GAIN_FACTOR
		0.0, -- RESERVE_FLEET
		0.0, -- NAVAL_INVASION_SUPPORT
	}
	
-- SPECIAL PROJECT DEFINES --
NDefines.NProject.RECRUIT_SCIENTIST_COST  = { 25, 25, 25, 25 } -- USED TO BE 25, 50, 75, 100